[workspace]
members = [
    "crates/kingfisher-core",
    "crates/kingfisher-rules",
    "crates/kingfisher-scanner",
    "crates/statsai-kingfisher",
]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.96"
license = "Apache-2.0"
authors = ["Mick Grove <mick.grove@mongodb.com>"]
homepage = "https://github.com/mongodb/kingfisher"
repository = "https://github.com/mongodb/kingfisher"
publish = false

[workspace.dependencies]
anyhow = "1.0"
thiserror = "2.0.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
schemars = "1.2"
regex = "1.12"
bstr = { version = "1.12", features = ["serde"] }
smallvec = { version = "1", features = ["const_generics", "const_new", "union"] }
parking_lot = "0.12"
tracing = "0.1"
vectorscan-rs = "0.0.6"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
ignore = "0.4"
walkdir = "2.5"
include_dir = "0.7"
sha1 = "0.11"
sha2 = "0.11"
hmac = "0.13"
base32 = "0.5.1"
base64 = "0.22"
percent-encoding = "2.3"
time = "0.3"
uuid = "1.23"
rand = "0.10"
hex = "0.4"
rustc-hash = "2.1"
http = "1.4"

[patch.crates-io]
vectorscan-rs = { path = "vendor/vectorscan-rs/vectorscan-rs" }
vectorscan-rs-sys = { path = "vendor/vectorscan-rs/vectorscan-rs-sys" }

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
